name: CI e Qualidade de Código (SonarCloud)

on:
  pull_request:
    branches:
      - master
      - develop
      - release

jobs:
  sonarcloud:
    name: Testes, Lint e SonarCloud
    runs-on: ubuntu-latest
    
    steps:
      - name: Clonar o repositório
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Obrigatório para o SonarCloud analisar o histórico

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: pip

      - name: Instalar Dependências
        run: |
          pip install -r requirements.txt
          pip install ruff pytest pytest-cov

      - name: Executar Testes e Gerar Cobertura
        run: pytest --cov=src --cov-report=xml

      - name: Análise do SonarCloud
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}